---
- name: copy ssh public key
  hosts: all
  tasks:
    - name: add public key to authorized_key file
      authorized_key:
        user: "root"
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
