version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    container_name: zookeeper
    hostname: zookeeper-${CLUSTER_NODE_ID}
    network_mode: host
    restart: "always"
    volumes:
      - /data/zookeeper/data/:/var/lib/zookeeper/data/
      - /data/zookeeper/log/:/var/lib/zookeeper/log/
    extra_hosts:
      - "zookeeper-1:${SERVER_1}"
      - "zookeeper-2:${SERVER_2}"
      - "zookeeper-3:${SERVER_3}"
    environment:
      ZOOKEEPER_SERVER_ID: ${CLUSTER_NODE_ID}
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888

  kafka:
    image: confluentinc/cp-kafka:5.5.3
    container_name: kafka
    hostname: kafka-${CLUSTER_NODE_ID}
    network_mode: host
    restart: "always"
    volumes:
      - /data/kafka/data/:/var/lib/kafka/data/
    extra_hosts:
      - "zookeeper-1:${SERVER_1}"
      - "zookeeper-2:${SERVER_2}"
      - "zookeeper-3:${SERVER_3}"
    environment:
      KAFKA_BROKER_ID: ${CLUSTER_NODE_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${CURRENT_SERVER}:9092
      #      100G
      KAFKA_LOG_RETENTION_BYTES: 107374182400
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "always"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "zookeeper-${CLUSTER_NODE_ID}:9092"
    extra_hosts:
      - "zookeeper-1:${SERVER_1}"
      - "zookeeper-2:${SERVER_2}"
      - "zookeeper-3:${SERVER_3}"
